### PR TITLE
Added more hotkeys and features and detailed them in github and Chrome Readme Files

### PR DESCRIPTION
**Pull request by regularWand**
Many videos on Youtube are 30 fps, so a toggle between the default 25 fps and 30 fps was added. Added a toggle between normal and 1/4 speed playback for easier video analysis before frame-by-frame skipping is engaged.

Also added a FRAMESKIP parameter to functions that can be increased or decreased by factors of 2 to allow fine-tuned or rapid frame skipping.

### CODE REVIEW

**Comment by CalumJEadie** [comment]
Cheers very much for this PR! Should I ignore #9?

**Comment by regularWand** [comment]
Yes you can ignore #9. I'm working on another update right now, with a fix for the onscreen buttons (which I broke), as well as onscreen reporting of the current fps and frameskip settings.

**Comment by CalumJEadie** [comment]
Sounds great. Give me a shout when it's a good point for me to review and
release the changes. Cheers!

-- 
Calum J. Eadie
calum@calumjeadie.com | 00447902918424

**Comment by regularWand** [comment]
You can go ahead and review the changes now.

I wanted to add one more feature for toggling the youtube player controls while the video is paused (when frame skipping is engaged), but I can't figure out how to remove the shadow that appears behind the controls. I will continue working on that in a separate branch.

**Comment by regularWand** [comment]
Hey Calum,

I ended up adding a few more features and reworking some things. I think now would be a good time to review the changes before adding anything else.

**Comment by CalumJEadie** [comment]
Cheers for the heads up @regularWand! Looking to forward to reviewing the changes over the next few days.

**Comment by CalumJEadie** [comment]
I've just checked out the improvements and they look great!

At the moment there are a couple of merge conflicts. It looks like I made some changes between when you forked from this repo and this pull request.

Would you mind bringing those commits in and checking they don't conflict with your changes?

**Comment by regularWand** [comment]
I've merged back the outstanding commits to my fork, and there are no more conflicts with the base branch. Hopefully nothing broke in the process.

**Comment by CalumJEadie** [comment]
I've run through the test cases described in https://github.com/CalumJEadie/frame-by-frame/blob/master/test/Test%20Suite.md and it looks great!

**Comment by CalumJEadie** [comment]
v1.1.0 is out! I tweaked the chrome web store description of the keyboard shortcuts and added shout outs to you and @tomchambers2. See 71ff94bc77581a9352a12a3e713ffea4ffb7c7b1.

Look forward to checking out the upcoming changes from #11!

**Comment by regularWand** [comment]
Awesome. I will be updating #11 shortly to include more features.

**Pull request merged**
